const String funnyQuotes[] = {
"\"When you are asked if you can do a job, tell 'em, 'Certainly I can!' Then get busy and find out how to do it.\" --Theodore Roosevelt",
"\"Confidence is 10% hard work and 90% delusion.\" --Tina Fey",
"\"Hard work never killed anybody, but why take a chance?\" --Edward Bergen",
"\"Oh, you hate your job? Why didn't you say so? There's a support group for that. It's called everybody, and they meet at the bar.\" --Drew Carey",
"\"There cannot be a crisis next week. My schedule is already full.\" --Henry Kissinger",
"\"I love deadlines. I like the whooshing sound they make as they fly by.\" --Douglas Adams",
"\"What I don't like about office Christmas parties is looking for a job the next day.\" --Phyllis Diller",
"\"By working faithfully eight hours a day, you may eventually get to be boss and work 12 hours a day.\" --Robert Frost",
"\"The road to success is always under construction.\" --Lily Tomlin",
"\"Every day I get up and look through the Forbes list of the richest people in America. If I'm not there, I go to work.\" --Robert Orben",
"\"Some people see things that are and ask, 'Why?' Some people dream of things that never were and ask, 'Why not?' Some people have to go to work and don't have time for all that.\" --George Carlin",
"\"No man goes before his time--unless the boss leaves early.\" --Groucho Marx",
"\"If hard work is the key to success, most people would rather pick the lock.\" --Claude MacDonald",
"\"The only place success comes before work is in the dictionary.\" --Vince Lombardi",
"\"Whatever you do, always give 100% -- unless you're donating blood.\" --Bill Murray",
"\"Find out what you like doing best and get someone to pay you for doing it.\" --Katharine Whitehorn",
"\"Be like a postage stamp; stick to one thing until you get there.\" --Josh Billings",
"\"Hard work spotlights the character of people: some turn up their sleeves, some turn up their noses, some don't turn up at all.\" --Sam Ewing",
"\"Hustle until your haters ask if you're hiring.\" --Steve Maraboli",
"\"The difference between try and triumph is just a little umph!\" --Marvin Phillips",
"\"Anyone can do any amount of work, provided it isn't the work he's supposed to be doing at that moment.\" --Robert Benchley",
"\"Work is the greatest thing in the world, so we should always save some of it for tomorrow.\" --Don Herold",
"\"Life moves pretty fast. If you don't stop and look around once in a while, you could miss it.\" --Ferris Bueller's Day Off (1986)",
"\"A little nonsense now and then is relished by the wisest men.\" --Willy Wonka and the Chocolate Factory (1971)",
"\"Why, sometimes I've believed six impossible things before breakfast.\" --Alice in Wonderland (1951)",
"\"If I'm not back in five minutes, just wait longer.\" --Ace Ventura: Pet Detective (1994)",
"\"Please. Have mercy. I've been wearing the same underwear since Tuesday.\" --Planes, Trains and Automobiles (1987)",
"\"My mama always said life was like a box of chocolates. You never know what you're gonna get.\" --Forrest Gump (1994)",
"\"Well, nobody's perfect.\" --Some Like It Hot (1959)",
"\"I learned a long time ago that worrying is like a rocking chair. It gives you something to do but it doesn't get you anywhere.\" --National Lampoon's Van Wilder (2002)",
"\"You want to get out of the hole? First you're going to have to put down the shovel.\" --Incredibles 2 (2018)",
"\"Just keep swimming.\" --Finding Nemo (2003)",
"\"A laugh can be a very powerful thing. Why, sometimes in life, it's the only weapon we have.\" --Who Framed Roger Rabbit? (1988)",
"\"If you can dodge a wrench, you can dodge a ball.\" --Dodgeball (2004)",
"\"Today is a good day to try.\" --The Hunchback of Notre Dame (1996)",
"\"Do not take life too seriously. You will never get out of it alive.\" --Elbert Hubbard",
"\"Life is hard. After all, it kills you.\" --Katharine Hepburn",
"\"I believe that if life gives you lemons, you should make lemonade, and try to find somebody whose life has given them vodka, and have a party.\" --Ron White",
"\"My therapist told me the way to achieve true inner peace is to finish what I start. So far I've finished two bags of M&Ms and a chocolate cake. I feel better already.\" --Dave Barry",
"\"Life is tough, darling. Life is hard. And we better laugh at everything, otherwise, we're going down the tube.\" --Joan Rivers",
"\"The secret of staying young is to live honestly, eat slowly and lie about your age.\" --Lucille Ball",
"\"Follow your passion. Stay true to yourself. Never follow anyone else's path unless you're in the woods and you're lost and you see a path. Then, by all means, follow that path.\" --Ellen DeGeneres",
"\"To succeed in life, you need three things: a wishbone, a backbone and a funny bone.\" --Reba McEntire",
"\"When I hear somebody sigh, 'Life is hard,' I am always tempted to ask, 'Compared to what?'\" --Sydney J. Harris",
"\"I have noticed that even people who claim everything is predetermined and that we can do nothing to change it look before they cross the road.\" --Stephen Hawking",
"\"A good rule to remember for life is that when it comes to plastic surgery and sushi, never be attracted by a bargain.\" --Graham Norton",
"\"You only live once, but if you do it right, once is enough.\" --Mae West",
"\"Don't go around saying the world owes you a living. The world owes you nothing. It was here first.\" --Mark Twain",
"\"My favorite thing to do on this planet is to play games. And if you don't enjoy games, then you're really missing the point of what this life is.\" --RuPaul",
"\"Life is short. Drive fast and leave a sexy corpse. That's one of my mottos.\" --Stanley Hudson, The Office",
"\"Life is just a big bowl of fancy assorted cashews!\" --Patrick Star, SpongeBob SquarePants",
"\"Your soul is like your appendix--I don't even use it!\" --Michael Kelso, That '70s Show",
"\"What am I scared of? I'm scared of the same thing that you are: everything.\" --George Costanza, Seinfeld",
"\"I'm a bit of a sucker for second chances. They're my first favorite kind of chance.\" --Jessica Day, New Girl",
"\"Nobody exists on purpose, nobody belongs anywhere, everybody's gonna die. Come watch TV.\" --Morty, Rick and Morty",
"\"Why can't parents just stay parents? You know? Why do they have to become people?\" --Rachel Green, Friends",
"\"We need to remember what's important in life: friends, waffles, work. Or waffles, friends, work. Doesn't matter, but work is third.\" --Leslie Knope, Parks and Recreation",
"\"Sometimes I'll start a sentence and I don't even know where it's going. I just hope I'll find it along the way.\" --Michael Scott, The Office",
"\"I'm not so good with the advice. Can I interest you in a sarcastic comment?\" --Chandler Bing, Friends",
"\"To alcohol! The cause of, and solution to, all of life's problems.\" --Homer Simpson, The Simpsons",
"\"I don't make the rules, ma'am. I just think them up and write them down.\" --Eric Cartman, South Park",
"\"All life ends in death, which we, as a species, are cursed with knowing. Resulting in ... something. Again, this is really not my field.\" --Ian Duncan, Community",
"\"Fate is just what you call it when you don't know the name of the person screwing you over.\" --Lois, Malcolm in the Middle",
"\"No thank you, I prefer to get high on life.\" --Millie Kentner, Freaks and Geeks",
"\"When life gives you lemons, make lemonade. I read that one on a can of lemonade. I like to think it applies to life.\" --Andy Dwyer, Parks and Recreation",
"\"I love a good nap. Sometimes it's the only thing getting me out of bed in the morning.\" --George Costanza, Seinfeld",
"\"Here's some advice I wish I woulda got when I was your age: Live every week like it's Shark Week.\" --Tracy Jordan, 30 Rock",
"\"If every instinct you have is wrong, then the opposite would have to be right.\" --Jerry Seinfeld, Seinfeld",
"\"I would do anything for my friends, which I think is how everyone in the world feels. Which is why I finally understand war.\" --Jeff Winger, Community",
"\"True friends are those who really know you but love you anyway.\" --Edna Buchanan",
"\"Lots of people want to ride with you in the limo, but what you want is someone who will take the bus with you when the limo breaks down.\" --Oprah Winfrey",
"\"When you're in jail, a good friend will be trying to bail you out. A best friend will be in the cell next to you saying, 'Damn, that was fun.'\" --Groucho Marx",
"\"There is nothing like puking with somebody to make you into old friends.\" --Sylvia Plath",
"\"We know our friends by their defects rather than by their merits.\" --William Somerset Maugham",
"\"'Best friend' isn't a person--it's a tier.\" --Mindy Kaling",
"\"Most of us don't need a psychiatric therapist as much as a friend to be silly with.\" --Robert Brault",
"\"Friendship is born at that moment when one person says to another, 'What? You too? I thought I was the only one!\" --C.S. Lewis",
"\"A loyal friend laughs at your jokes when they're not so good, and sympathizes with your problems when they're not so bad.\" --Arnold H. Glasgow",
"\"If you can survive 11 days in cramped quarters with a friend and come out laughing, your friendship is the real deal.\" --Oprah Winfrey",
"\"There is nothing better than a friend, unless it is a friend with chocolate.\" --Linda Grayson",
"\"You find out who your real friends are when you're involved in a scandal.\" --Elizabeth Taylor",
"\"A true friend is someone that thinks you are a good egg even though he knows that you are slightly cracked.\" --Bernard Meltzer",
"\"It is one of the blessings of old friends that you can afford to be stupid with them.\" --Ralph Waldo Emerson",
"\"Friendship is like money--easier made than kept.\" --Samuel Butler",
"\"It's important to our friends to believe that we are unreservedly frank with them, and important to the friendship that we are not.\" --Mignon McLaughlin",
"\"You can always tell a real friend: When you've made a fool of yourself he doesn't feel you've done a permanent job.\" --Laurence J. Peter",
"\"There are few things in life harder to find and more important to keep than love. Well, love and a birth certificate.\" --Barack Obama",
"\"Marriage: a friendship recognized by the police.\" --Robert Louis Stevenson",
"\"I love being married. It's so great to find one special person you want to annoy for the rest of your life.\" --Rita Rudner",
"\"Honesty is the key to a relationship. If you can fake that, you're in.\" --Richard Jeni",
"\"When you're in love, it's the most glorious two-and-a-half days of your life.\" --Richard Lewis",
"\"You can't buy love, but you can pay heavily for it.\" --Henry Youngman",
"\"If love is the answer, could you please rephrase the question?\" --Lily Tomlin",
"\"Love conquers all things except poverty and toothache.\" --Mae West",
"\"The heart has its reasons, of which reason knows nothing.\" --Blaise Pascal",
"\"Love can change a person the way a parent can change a baby--awkwardly, and often with a great deal of mess.\" --Lemony Snicket",
"\"Love is like an hourglass, with the heart filling up as the brain empties.\" --Jules Renard",
"\"Love is a two-way street constantly under construction.\" --Carroll Bryant",
"\"True love comes quietly, without banners or flashing lights. If you hear bells, get your ears checked.\" --Erich Segal",
"\"All you need is love. But a little chocolate now and then doesn't hurt.\" --Charles M. Schulz"
};
